language: c

compiler:
  - gcc

before_script:
  - cmake CMakeLists.txt

script:
  - make

before_deploy:
  #Setup git user and tag commit
  - git config --local user.name "TravisCI"
  - git config --local user.email "nicholas@rosati.xyz"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $TOKEN
  file: "CaseChanger"
  skip_cleanup: true
  on:
      tags: false