language: c

compiler:
  - gcc

before_script:
  - cmake CMakeLists.txt

script:
  - make

deploy:
  provider: releases
  api_key: $TOKEN
  file: "CaseChanger"
  skip_cleanup: true
  on:
      tags: true